version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
  redis:
    image: redis
    container_name: redis_cache
    ports:
      - "6379:6379"
  app:
    build:
      context: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis